In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#numpy array

arr = np.array( [ [1,2] , [3,4]] )
arr

array([[1, 2],
       [3, 4]])

In [ ]:
df = pd.DataFrame(arr, columns = ["A","B"])
df

   A  B
0  1  2
1  3  4

# Series

In [ ]:
s = pd.Series([10,20,30], index = ["a", "b" , "c"])
s

a    10
b    20
c    30
dtype: int64

In [ ]:
s["c"]

np.int64(30)

In [ ]:
for indx in s.index:
  s[indx] = s[indx] +10

a
b
c

In [ ]:
s = s+10
s

a    30
b    40
c    50
dtype: int64

# problem :

Dataframe

In [ ]:
df = pd.DataFrame(
    {
        "Name" : ["A","B"],
        "Age" : [20,21]
    }
)
df

  Name  Age
0    A   20
1    B   21

In [ ]:
print(type( df["Name"] ))

<class 'pandas.core.series.Series'>

In [ ]:
print( "Index ", df.index)

Index  RangeIndex(start=0, stop=2, step=1)

In [ ]:
df1 = pd.Series([1,2], index = ["a","b"])
df2 = pd.Series([3,4], index = ["a","b"])

print(df1+df2)

a    4
b    6
dtype: int64

# CSV file

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'students-performance-in-exams' dataset.
Path to dataset files: /kaggle/input/students-performance-in-exams

In [ ]:
df = pd.read_csv("/kaggle/input/students-performance-in-exams/StudentsPerformance.csv")

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

#loc and iloc

In [ ]:
df = pd.DataFrame(
    {
        "Name" : ["A","B"],
        "Age" : [20,21]
    },
    index = ["x","y"]
)
df

  Name  Age
x    A   20
y    B   21

In [ ]:
df["Name"]

x    A
y    B
Name: Name, dtype: object

In [ ]:
df["Age"]

x    20
y    21
Name: Age, dtype: int64

In [ ]:
df.loc["x"]

Name     A
Age     20
Name: x, dtype: object

In [ ]:
df.iloc[0:2]

  Name  Age
x    A   20
y    B   21

In [ ]:
#get specific cell
df.iloc[0,0]

'A'

In [ ]:
for i in range(len(df)):
  print(df.iloc[i])

Name     A
Age     20
Name: x, dtype: object
Name     B
Age     21
Name: y, dtype: object

In [ ]:
# get multiple rows
df.loc[ ["x","y"] ]

  Name  Age
x    A   20
y    B   21

In [ ]:
df.loc["y","Age"]

np.int64(21)

In [ ]:
# Conditional filtering
df.loc[ df["Age"] > 18 ]

  Name  Age
x    A   20
y    B   21

# Data manipulation

In [ ]:
df = pd.DataFrame(
    {
        "Name" : ["A","B"],
        "Age" : [20,21]
    }
)


#add new columns
df["Marks"] = [80,90]

df

  Name  Age  Marks
0    A   20     80
1    B   21     90

In [ ]:
#drop columns

df2 = df.drop("Marks",axis = 1)
df2

  Name  Age
0    A   20
1    B   21

In [ ]:
# Filtering
df = pd.DataFrame({
    "Name" : ["A","B","C"] ,
    "Age" : [18,21,25]

})
df

  Name  Age
0    A   18
1    B   21
2    C   25

In [ ]:
filtered_df = df[ df["Age"] > 18  ]
filtered_df

  Name  Age
1    B   21
2    C   25

# Sorting

In [ ]:
df = pd.DataFrame({
    "Name" : ["A","B","C"] ,
    "Age" : [25,21,18]

})
df

  Name  Age
0    A   25
1    B   21
2    C   18

In [ ]:
# age

sorted_df = df.sort_values( by ="Age" )
sorted_df

  Name  Age
2    C   18
1    B   21
0    A   25

# Iteration

In [ ]:
for index , row in df.iterrows():
  print( row["Name"], row["Age"]  )

A 25
B 21
C 18

#vectorization

In [ ]:
df = pd.DataFrame({
    "Marks" : [50,60,70]
                   })
df

   Marks
0     50
1     60
2     70

In [ ]:
#vectorized operation
df["Marks"] = df["Marks"] * 2
df

   Marks
0    200
1    240
2    280

# Mini project

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 67, 90, 45, 88]
}

df = pd.DataFrame(data)
df

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     67
2  Charlie   19     90
3    David   22     45
4      Eva   20     88

In [ ]:
# add a grade columns

def assign_grade(marks):
  if marks >=80:
    return "A"
  elif marks >=60:
    return "B"
  else:
    return "C"


df["Grade"] = df["Marks"].apply(assign_grade)

In [ ]:
df

      Name  Age  Marks Grade
0    Alice   20     85     A
1      Bob   21     67     B
2  Charlie   19     90     A
3    David   22     45     C
4      Eva   20     88     A

In [ ]:
# Filter Student

top_students = df[ df['Marks'] > 80 ]
top_students

      Name  Age  Marks Grade
0    Alice   20     85     A
2  Charlie   19     90     A
4      Eva   20     88     A

In [ ]:
#sort student

sorted_df = df.sort_values( by="Marks", ascending= True )
sorted_df

      Name  Age  Marks Grade
3    David   22     45     C
1      Bob   21     67     B
0    Alice   20     85     A
4      Eva   20     88     A
2  Charlie   19     90     A

In [ ]:
#average marks

avg_marks = df["Marks"].mean()
avg_marks

np.float64(75.0)

In [ ]:
#save as a csv file

df.to_csv("Student_output.csv",index=False)

# Advance

In [ ]:
sales_data = {
    "Order_ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Customer_ID": [101, 102, 101, 103, 104, 102, 105, 101],
    "Product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Tablet", "Laptop", "Phone"],
    "Category": ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics"],
    "Price": [800, 500, 300, 850, 520, 310, 780, 510],
    "Quantity": [1, 2, 1, 1, 1, 3, 1, 2],
    "Date": ["2024-01-05", "2024-01-10", "2024-02-15", "2024-02-20", "2024-03-05", "2024-03-15", "2024-04-01", "2024-04-10"]
}
df = pd.DataFrame(sales_data)
df

   Order_ID  Customer_ID Product     Category  Price  Quantity        Date
0         1          101  Laptop  Electronics    800         1  2024-01-05
1         2          102   Phone  Electronics    500         2  2024-01-10
2         3          101  Tablet  Electronics    300         1  2024-02-15
3         4          103  Laptop  Electronics    850         1  2024-02-20
4         5          104   Phone  Electronics    520         1  2024-03-05
5         6          102  Tablet  Electronics    310         3  2024-03-15
6         7          105  Laptop  Electronics    780         1  2024-04-01
7         8          101   Phone  Electronics    510         2  2024-04-10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     8 non-null      int64
 1   Customer_ID  8 non-null      int64
 2   Product      8 non-null      object
 3   Category     8 non-null      object
 4   Price        8 non-null      int64
 5   Quantity     8 non-null      int64
 6   Date         8 non-null      object
dtypes: int64(4), object(3)
memory usage: 580.0+ bytes

In [ ]:
df["Date"] = pd.to_datetime( df["Date"] )

In [ ]:
df.dtypes

Order_ID                int64
Customer_ID             int64
Product                object
Category               object
Price                   int64
Quantity                int64
Date           datetime64[ns]
dtype: object