In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('/content/100_Unique_QA_Dataset.csv')
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [ ]:
#token

def tokenizer(text):
  text=text.lower()
  text=text.replace(".","")
  text=text.replace(",","")
  text=text.replace("?","")
  text=text.replace("!","")
  return text.split()

In [ ]:
tokenizer("What is the capital of France?")

['what', 'is', 'the', 'capital', 'of', 'france']

In [ ]:
#Vocab
vocab={'UNK':0}
def build_vocab(row):
  tokenize_ques=tokenizer(row['question'])
  tokenize_ans=tokenizer(row['answer'])
  merge=tokenize_ques+tokenize_ans
  for word in merge:
    if word not in vocab:
      vocab[word]=len(vocab)

In [ ]:
df.apply(build_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [ ]:
vocab

{'UNK': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 "'to": 12,
 'kill': 13,
 'a': 14,
 "mockingbird'": 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 "'1984'": 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299792458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 "'starry": 130,
 "night'": 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'to': 143,
 'step': 144,
 'moon': 145,
 'armstrong': 146,
 'main': 147,
 'ingredient': 148,
 'guacamole': 149,
 'avocado': 150,
 'sides': 151,
 'does': 152,
 'hexagon': 153,
 'have': 154,
 '6': 155,
 'china': 156,
 'yuan': 157,
 "'pride": 158,
 'and': 159,
 "prejudice'": 160,
 'jane-austen': 161,
 'iron': 162,
 'fe': 163,
 'hardest': 164,
 'natural': 165,
 'substance': 166,
 'diamond': 167,
 'continent': 168,
 'by': 169,
 'area': 170,
 'asia': 171,
 'president': 172,
 'states': 173,
 'george-washington': 174,
 'bird': 175,
 'its': 176,
 'ability': 177,
 'mimic': 178,
 'sounds': 179,
 'parrot': 180,
 'longest-running': 181,
 'animated': 182,
 'tv': 183,
 'show': 184,
 'simpsons': 185,
 'vaticancity': 186,
 'most': 187,
 'moons': 188,
 'saturn': 189,
 "'romeo": 190,
 "juliet'": 191,
 'shakespeare': 192,
 "earth's": 193,
 'atmosphere': 194,
 'nitrogen': 195,
 'bones': 196,
 'adult': 197,
 'human': 198,
 'body': 199,
 '206': 200,
 'metal': 201,
 'liquid': 202,
 'at': 203,
 'room': 204,
 'temperature': 205,
 'mercury': 206,
 'russia': 207,
 'moscow': 208,
 'electricity': 209,
 'benjamin-franklin': 210,
 'second-largest': 211,
 'land': 212,
 'color': 213,
 'ripe': 214,
 'banana': 215,
 'yellow': 216,
 'month': 217,
 '28': 218,
 'days': 219,
 'common': 220,
 'february': 221,
 'study': 222,
 'living': 223,
 'organisms': 224,
 'called': 225,
 'biology': 226,
 'home': 227,
 'great': 228,
 'wall': 229,
 'bees': 230,
 'collect': 231,
 'from': 232,
 'flowers': 233,
 'nectar': 234,
 'opposite': 235,
 "'day'": 236,
 'night': 237,
 'south': 238,
 'korea': 239,
 'seoul': 240,
 'bulb': 241,
 'edison': 242,
 'humans': 243,
 'breathe': 244,
 'survival': 245,
 'oxygen': 246,
 '144': 247,
 '12': 248,
 'pyramids': 249,
 'giza': 250,
 'egypt': 251,
 'sea': 252,
 'creature': 253,
 'eight': 254,
 'arms': 255,
 'octopus': 256,
 'holiday': 257,
 'celebrated': 258,
 'december': 259,
 '25': 260,
 'christmas': 261,
 'yen': 262,
 'legs': 263,
 'spider': 264,
 'sport': 265,
 'uses': 266,
 'net': 267,
 'ball': 268,
 'hoop': 269,
 'basketball': 270,
 'kangaroos': 271,
 'female': 272,
 'minister': 273,
 'uk': 274,
 'margaretthatcher': 275,
 'fastest': 276,
 'animal': 277,
 'cheetah': 278,
 'periodic': 279,
 'table': 280,
 'spain': 281,
 'madrid': 282,
 'closest': 283,
 'sun': 284,
 'father': 285,
 'computers': 286,
 'charlesbabbage': 287,
 'mexico': 288,
 'mexicocity': 289,
 'colors': 290,
 'rainbow': 291,
 'musical': 292,
 'instrument': 293,
 'black': 294,
 'white': 295,
 'keys': 296,
 'piano': 297,
 'americas': 298,
 '1492': 299,
 'christophercolumbus': 300,
 'disney': 301,
 'character': 302,
 'long': 303,
 'nose': 304,
 'grows': 305,
 'it': 306,
 'when': 307,
 'lying': 308,
 'pinocchio': 309,
 'directed': 310,
 'movie': 311,
 "'titanic'": 312,
 'jamescameron': 313,
 'superhero': 314,
 'also': 315,
 'dark': 316,
 'knight': 317,
 'batman': 318,
 'brasilia': 319,
 'fruit': 320,
 'king': 321,
 'fruits': 322,
 'mango': 323,
 'eiffel': 324,
 'tower': 325}

In [ ]:
# convert words to numerical indecis
def text_to_indices(text,vocab):
  indexed_text=[]
  for token in tokenizer(text):
    if token not in vocab:
      indexed_text.append(vocab['UNK'])
    else:
      indexed_text.append(vocab[token])
  return indexed_text

In [ ]:
import torch
from torch.utils.data import Dataset,DataLoader

In [ ]:
class QADataset(Dataset):
  def __init__(self,df,vocab):
    self.df=df
    self.vocab=vocab
  def __len__(self):
    return len(self.df)
  def __getitem__(self,idx):
    row=self.df.iloc[idx]
    question=text_to_indices(row['question'],self.vocab)
    answer=text_to_indices(row['answer'],self.vocab)
    return torch.tensor(question),torch.tensor(answer)

In [ ]:
dataset=QADataset(df,vocab)

In [ ]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [ ]:
for question,answer in dataloader:
  print(question,answer)

tensor([[ 42, 257,   2, 258,  83, 259, 260]]) tensor([[261]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[262]])
tensor([[ 10,  11, 158, 159, 160]]) tensor([[161]])
tensor([[ 10, 310,   3, 311, 312]]) tensor([[313]])
tensor([[ 10, 140,   3, 141, 172,   5,   3,  70, 173]]) tensor([[174]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([[136]])
tensor([[ 78,  79, 290,  81,  19,  14, 291]]) tensor([[85]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[186]])
tensor([[ 42, 292, 293, 118, 294, 159, 295, 296]]) tensor([[297]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[ 42, 301, 302, 118,  14, 303, 304, 159, 305, 306, 307, 308]]) tensor([[309]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([[52]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 42, 265, 266,  14, 267, 268, 159, 269]]) tensor([[270]])
tensor([[ 42, 137,   2, 227, 143,   3, 228, 229]]) tensor([[156]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[ 10, 140,   3, 141, 142, 143, 144,  83,   3, 145]]) tensor([[146]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([[128]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([[36]])
tensor([[ 42, 320,   2,  62,  63,   3, 321,   5, 322]]) tensor([[323]])
tensor([[ 10,  11, 190, 159, 191]]) tensor([[192]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[  1,   2,   3, 147,  86,  19, 193, 194]]) tensor([[195]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[  1,   2,   3,   4,   5, 238, 239]]) tensor([[240]])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([[110]])
tensor([[  1,   2,   3,  37,  38,  39, 162]]) tensor([[163]])
tensor([[ 42,   2,   3, 211, 137, 169, 212, 170]]) tensor([[113]])
tensor([[  1,   2,   3,  33,  34,   5, 247]]) tensor([[248]])
tensor([[ 10, 140,   3, 141, 272,  93, 273,   5,   3, 274]]) tensor([[275]])
tensor([[ 42,  18,   2,   3, 283, 143,   3, 284]]) tensor([[206]])
tensor([[ 42, 137,   2, 138,  39, 176, 271]]) tensor([[99]])
tensor([[ 42, 137, 118,   3, 249,   5, 250]]) tensor([[251]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[10, 96,  3, 97]]) tensor([[98]])
tensor([[ 42,  18, 118,   3, 187, 188]]) tensor([[189]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([[72]])
tensor([[ 42, 314,   2, 315,  62,  63,   3, 316, 317]]) tensor([[318]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[ 42,   2,   3, 276, 212, 277]]) tensor([[278]])
tensor([[ 10,  75, 209]]) tensor([[210]])
tensor([[  1,   2,   3,  69,   5, 156]]) tensor([[157]])
tensor([[ 42, 201,   2,  14, 202, 203, 204, 205]]) tensor([[206]])
tensor([[  1,   2,   3, 213,   5,  14, 214, 215]]) tensor([[216]])
tensor([[  1,   2,   3, 235,   5, 236]]) tensor([[237]])
tensor([[ 42,  86,  87, 243, 244,  19,  39, 245]]) tensor([[246]])
tensor([[  1,   2,   3, 222,   5, 223, 224, 225]]) tensor([[226]])
tensor([[  1,   2,   3,   4,   5, 288]]) tensor([[289]])
tensor([[ 42, 137,   2,  62,  39,   3, 324, 325]]) tensor([[6]])
tensor([[ 42, 101,   2,   3,  17]]) tensor([[102]])
tensor([[ 42, 175,   2,  62,  39, 176, 177, 143, 178, 179]]) tensor([[180]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[ 10,  75,   3, 298,  19, 299]]) tensor([[300]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[  1,   2,   3, 181, 182, 183, 184]]) tensor([[185]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[ 78,  79, 196,  81,  19,   3, 197, 198, 199]]) tensor([[200]])
tensor([[ 42, 168,   2,   3,  17, 169, 170]]) tensor([[171]])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([[319]])
tensor([[  1,   2,   3, 164, 165, 166,  83,  84]]) tensor([[167]])
tensor([[  1,   2,   3,   4,   5, 207]]) tensor([[208]])
tensor([[  1,   2,   3,   4,   5, 281]]) tensor([[282]])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[  1,   2,   3, 147, 148,  19, 149]]) tensor([[150]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([[74]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 279, 280]]) tensor([[121]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[ 10,   2,  62,  63,   3, 285,   5, 286]]) tensor([[287]])
tensor([[ 10,  96,   3, 104, 241]]) tensor([[242]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[ 78,  79, 151, 152,  14, 153, 154]]) tensor([[155]])
tensor([[ 78,  79, 263, 152,  14, 264, 154]]) tensor([[36]])
tensor([[ 42, 217, 118, 218, 219,  19,  14, 220,  43]]) tensor([[221]])
tensor([[ 42, 252, 253, 118, 254, 255]]) tensor([[256]])
tensor([[  1,  87, 230, 231, 232, 233]]) tensor([[234]])

In [ ]:
import torch.nn as nn

In [ ]:
class SimpleRNN(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding=nn.Embedding(vocab_size,embedding_dim=50)
    self.rnn=nn.RNN(50,64,batch_first=True)
    self.fc=nn.Linear(64,vocab_size)
  def forward(self,question):
    embeded_question=self.embedding(question)
    hidden,final=self.rnn(embeded_question)
    output=self.fc(final.squeeze(0))
    return output

In [ ]:
learning_rate=0.001
epochs=20

In [ ]:
model=SimpleRNN(len(vocab))
loss_fn=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [ ]:
# training loop
for epoch in range(epochs):
  total_loss=0
  for question,answer in dataloader:
    optimizer.zero_grad()
    #forward pass
    output=model(question)
    # loss
    loss=loss_fn(output,answer[0])
    # gradients
    loss.backward()
    #update
    optimizer.step()
    total_loss+=loss.item()
  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 523.414264
Epoch: 2, Loss: 451.505186
Epoch: 3, Loss: 372.017580
Epoch: 4, Loss: 313.409217
Epoch: 5, Loss: 261.993646
Epoch: 6, Loss: 214.285829
Epoch: 7, Loss: 171.732493
Epoch: 8, Loss: 134.515727
Epoch: 9, Loss: 103.720474
Epoch: 10, Loss: 80.490430
Epoch: 11, Loss: 62.973930
Epoch: 12, Loss: 49.888226
Epoch: 13, Loss: 40.221608
Epoch: 14, Loss: 33.129421
Epoch: 15, Loss: 27.396166
Epoch: 16, Loss: 23.008432
Epoch: 17, Loss: 19.442821
Epoch: 18, Loss: 16.699340
Epoch: 19, Loss: 14.336977
Epoch: 20, Loss: 12.407089

In [ ]:
def predict(model,question,threshold=0.5):
  # conver question to numbers
  numerical_question= text_to_indices(question,vocab)
  #tensor
  question_tensor=torch.tensor(numerical_question).unsqueeze(0)
  #send to model
  output=model(question_tensor)
  #probabilitys
  probs=torch.nn.functional.softmax(output,dim=1)
  value,index=torch.max(probs,dim=1)
  if value<threshold:
    print("I do not know")
  else:
    print(list(vocab.keys())[index])

In [ ]:
predict(model,"what is the capital of Bangladesh?")

I do not know